# Generated by Django 5.1.2 on 2024-10-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_users_user_users_is_guest_users_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_since', models.DateTimeField(auto_now_add=True)),
                ('matches_play_against', models.PositiveIntegerField(default=0)),
                ('user1_win', models.PositiveIntegerField(default=0)),
                ('matches_play_together', models.PositiveIntegerField(default=0)),
                ('matches_win_together', models.PositiveIntegerField(default=0)),
                ('friend_users', models.ManyToManyField(to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='users.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='users.users')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
