# Generated by Django 5.1.2 on 2024-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_since', models.DateTimeField(auto_now_add=True)),
                ('matches_play_against', models.PositiveIntegerField(default=0)),
                ('user1_win', models.PositiveIntegerField(default=0)),
                ('matches_play_together', models.PositiveIntegerField(default=0)),
                ('matches_win_together', models.PositiveIntegerField(default=0)),
                ('friends', models.ManyToManyField(to='users.users')),
            ],
        ),
    ]
