# Generated by Django 5.1.2 on 2024-10-13 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='friend_users',
            new_name='users',
        ),
    ]
