# Generated by Django 5.1.2 on 2024-10-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_friend_users_friends_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='users',
            new_name='friends',
        ),
    ]
