# Generated by Django 5.1.2 on 2024-10-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_rename_users_friends_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequests',
        ),
    ]
