services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:300"
    volumes:
      - /Users/florianguiramand/Desktop/ft_transcendence/postgre_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=fguirama
      - POSTGRES_PASSWORD=123456
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence-network
    driver: bridge

volumes:
  database-volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/florianguiramand/Desktop/ft_transcendence/postgre_data/
