services:
  main-django:
    image: main_django
    build:
      context: transcendence
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
      - "443:443"
    networks:
      - "transcendence"
    volumes:
      - site-volume:/site


  users-database:
    image: users-database
    build:
      context: site/users-database
      dockerfile: Dockerfile
    volumes:
      - users-db-volume:/db
    restart: on-failure
    networks:
      - "transcendence"
    depends_on:
    - main-django
  matches-database:
    image: matches-database
    build:
      context: site/matches-database
      dockerfile: Dockerfile
    volumes:
      - matches-db-volume:/db
    restart: on-failure
    networks:
      - "transcendence"
    depends_on:
      - main-django


networks:
  transcendence:
    name: transcendence-network
    driver: bridge

volumes:
  users-db-volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/basil/data/users-db
  matches-db-volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/basil/data/matches-db
  site-volume:
    name: site-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/basil/data/site


#  database-volume:
#    name: database-volume
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: $HOME/data/database
#  wordpress-volume:
#    name: wordpress-volume
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: $HOME/data/wordpress
