services:
  project-main-django:
    image: project-main-django
    build: ./project-main
    restart: on-failure
    ports:
      - "2006:2006"
    networks:
      - transcendence
    volumes:
      - project-main-volume:/project-main

volumes:
  project-main-volume:
    name: project-main-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./project-main/project-main-django

networks:
  transcendence:
    name: transcendence-network
    driver: bridge