services:

  auth:
    container_name: transcendence-auth
    depends_on:
      - auth_db
    build:
      context: requirements/auth
      dockerfile: Dockerfile
    restart: always
    volumes:
      - auth-volume:/code
    ports:
      - "8000:8000"
    networks:
      - transcendence-network
      - auth-network

  auth_db:
    image: postgres:14
    restart: always
    # volumes:
    #   - "auth-db-volume:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=fguirama # todo : use .env
      - POSTGRES_PASSWORD=123456 # todo : use .env
    networks:
      - auth-network

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge
  auth-network:
    name: auth-network
    driver: bridge

volumes:
  auth-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './requirements/auth/django/'
  # auth-db-volume:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: './requirements/auth_db/'
