services:
  frontend:
    build: ./requirements/frontend
    ports:
      - "4443:443"
    volumes:
      - frontend_volume:/var/www/html
      - ./requirements/frontend/Caddyfile:/etc/caddy/Caddyfile



  # users:
  #   image: users
  #   depends_on:
  #     - users_db
  #   build:
  #     context: requirements/users
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   # ports:
  #   #   - "8000:8000"
  #   #   - "443:443"
  #   networks:
  #     - "transcendence_nw"
  #     - "users_nw"
  #   volumes:
  #     - site-volume:/site
  # users_db:
  #   image: postgres:14
  #   restart: on_failure
  #   ports:
  #     - "5432:300"
  #   volumes:
  #     - user_db_volume:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=ft_transcendence_db
  #     - POSTGRES_USER=fguirama
  #     - POSTGRES_PASSWORD=123456
  #   networks:
  #     - authentication_db_nw

  # game:
  #   image: game
  #   depends_on:
  #     - game_db
  #   build:
  #     context: requirements/game
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   # ports:
  #   #   - "8000:8000"
  #   #   - "443:443"
  #   networks:
  #     - "transcendence_nw"
  #     - "game_nw"
  #   volumes:
  #     - site-volume:/site
  # game_db:
  #   image: postgres:14
  #   restart: always
  #   ports:
  #     - "5432:300"
  #   volumes:
  #     - game_db_volume:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=ft_transcendence_db
  #     - POSTGRES_USER=fguirama
  #     - POSTGRES_PASSWORD=123456
  #   networks:
  #     - game_nw

  matchmaking:
    image: matchmaking
    build:
      context: requirements/matchmaking
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8003:8000"
    networks:
      - "transcendence_nw"
    volumes:
      - matchmaking_volume:/code

  chat:
    image: chat
    depends_on:
      - chat_db
    build:
      context: requirements/chat
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:8000"
    networks:
      - "transcendence_nw"
      - "chat_nw"
    volumes:
      - chat_volume:/code
  chat_db:
    image: postgres:14
    restart: always
    volumes:
      - chat_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=fguirama
      - POSTGRES_PASSWORD=123456
    networks:
      - chat_nw

  authentication:
    image: authentication
    depends_on:
      - authentication_db
    build:
      context: requirements/authentication
      dockerfile: Dockerfile
    restart: always
    volumes:
      - authentication_volume:/code
    ports:
      - "8000:8000"
    networks:
      - transcendence_nw
      - auth_nw
  authentication_db:
    image: postgres:14
    restart: always
    volumes:
      - authentication_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=fguirama
      - POSTGRES_PASSWORD=123456
    networks:
      - auth_nw

  statistics:
    image: requirements/algo-sats
    restart: always
    build:
      context: requirements/algo-stats
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - statistics_volume:/code
    networks:
      - statistics_nw
      - transcendence_nw
  statistics_db:
    image: postgres:14
    restart: always
    volumes:
      - statistics_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=fguirama
      - POSTGRES_PASSWORD=123456
    networks:
      - statistics_nw

networks:
  transcendence_nw:
    name: transcendence_global_network
    driver: bridge
  auth_nw:
    name: authentication_db_network
    driver: bridge
  statistics_nw:
    name: statistics_network
    driver: bridge
  game_nw:
    name: game_network
    driver: bridge
  chat_nw:
    name: chat_network
    driver: bridge
  users_nw:
    name: users_network
    driver: bridge

volumes:
  frontend_volume:
    name: frontend_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/frontend/static/
  caddyfile_volume:
    name: caddyfile_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/frontend/Caddyfile
  users_db_volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/transcendence/users
  game_db_volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/transcendence/game
  chat_db_volume:
    name: database-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/transcendence/chat
  chat_volume:
    name: chat-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/chat/chat
  authentication_db_volume:
    name: auth_db_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/transcendence/auth
  authentication_volume:
    name: auth_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/authentication/auth
  statistics_db_volume:
    name: stat_db-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/transcendence/stats
  statistics_volume:
    name: stat-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/algo-stats/algo_stats
  matchmaking_volume:
    name: stat-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: requirements/matchmaking/matchmaking
