# Generated by Django 5.1.1 on 2024-10-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='participants',
            field=models.ManyToManyField(to='users.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chats'),
        ),
    ]
