# Generated by Django 5.1.2 on 2024-10-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
