# Generated by Django 5.1.2 on 2024-11-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, unique=True)),
                ('max_participants', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_mode', models.CharField(max_length=11)),
                ('match_type', models.CharField(max_length=3)),
                ('bo', models.IntegerField(default=1)),
                ('game_time', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_code', models.CharField(editable=False, max_length=5)),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=20)),
                ('creator', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(default='Team A')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobby')),
            ],
        ),
    ]
