# Generated by Django 5.1.2 on 2024-11-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, unique=True)),
                ('max_participants', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_mode', models.CharField(max_length=11)),
                ('match_type', models.CharField(max_length=3)),
                ('bo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('creator', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(default=None, null=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobby')),
            ],
        ),
    ]
