# Generated by Django 5.1.2 on 2024-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='match_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lobbyparticipants',
            name='team',
            field=models.CharField(default='Team A'),
        ),
    ]
