# Generated by Django 5.1.2 on 2024-11-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_remove_lobby_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyparticipants',
            name='lobby_code',
        ),
    ]
