# Generated by Django 5.1.2 on 2024-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_lobby_match_type_alter_lobbyparticipants_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_mode',
            field=models.CharField(max_length=11),
        ),
    ]
