# Generated by Django 5.1.2 on 2024-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_alter_lobby_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_mode',
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
