# Generated by Django 5.1.2 on 2024-10-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_lobby_game_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobbyparticipants',
            old_name='is_admin',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='code',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='lobbyparticipants',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobby'),
        ),
    ]
