# Generated by Django 5.1.2 on 2024-10-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_rename_is_admin_lobbyparticipants_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyparticipants',
            name='username',
        ),
    ]
