# Generated by Django 5.1.2 on 2024-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_remove_lobbyparticipants_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyparticipants',
            name='is_guest',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
