# Generated by Django 5.1.2 on 2024-10-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_lobbyparticipants_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='game_time',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='lobbyparticipants',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobbyparticipants',
            name='team',
            field=models.CharField(default=None, null=True),
        ),
    ]
