# Generated by Django 5.1.2 on 2024-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20, unique=True)),
                ('url', models.FilePathField()),
                ('small', models.FilePathField()),
                ('medium', models.FilePathField()),
                ('large', models.FilePathField()),
            ],
        ),
    ]
