# Generated by Django 5.1.2 on 2024-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('trophies', models.IntegerField()),
                ('game_mode', models.CharField(max_length=50)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
