# Generated by Django 5.1.2 on 2024-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
