# Generated by Django 5.1.2 on 2024-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='trophies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
