# Generated by Django 5.1.2 on 2024-10-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accept_friend_request', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('is_in_game', models.CharField(default=None, max_length=5, null=True)),
                ('last_online', models.DateTimeField(auto_now_add=True)),
                ('coins', models.IntegerField(default=100)),
                ('trophy', models.IntegerField(default=0)),
                ('current_rank', models.IntegerField(default=None, null=True)),
                ('highest_rank', models.IntegerField(default=None, null=True)),
                ('blocked_users', models.ManyToManyField(blank=True, default=None, to='users.users')),
                ('own_profile_pictures', models.ManyToManyField(blank=True, default=None, related_name='own_profile_pictures', to='profile_pictures.profilepictures')),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_pictures.profilepictures')),
            ],
        ),
    ]
