# Generated by Django 5.1.2 on 2024-11-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accept_friend_request', models.BooleanField(default=True)),
                ('accept_chat_state', models.SmallIntegerField(default=3)),
                ('is_online', models.BooleanField(default=False)),
                ('game_playing', models.CharField(default=None, max_length=5, null=True)),
                ('last_online', models.DateTimeField(auto_now_add=True)),
                ('coins', models.IntegerField(default=100)),
                ('trophies', models.IntegerField(default=0)),
                ('current_rank', models.IntegerField(default=None, null=True)),
                ('highest_rank', models.IntegerField(default=None, null=True)),
                ('own_profile_pictures', models.ManyToManyField(blank=True, default=None, related_name='own_profile_pictures', to='profile_pictures.profilepictures')),
                ('profile_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_pictures.profilepictures')),
            ],
        ),
    ]
