# Generated by Django 5.1.2 on 2024-10-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_in_game',
            new_name='game_playing',
        ),
    ]
