# Generated by Django 5.1.2 on 2024-10-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_user_users_is_guest_users_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='blocked_users',
        ),
    ]
