# Generated by Django 5.1.2 on 2024-10-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
