# Generated by Django 5.1.2 on 2024-10-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accept_chat_state',
            field=models.SmallIntegerField(default=2),
        ),
    ]
