# Generated by Django 5.1.2 on 2024-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_accept_chat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='accept_chat_state',
            field=models.SmallIntegerField(default=3),
        ),
    ]
