# Generated by Django 5.1.2 on 2024-10-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_accept_chat_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='trophy',
            new_name='trophies',
        ),
    ]
