# Generated by Django 5.1.2 on 2024-10-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatparticipants'),
        ),
    ]
