# Generated by Django 5.1.2 on 2024-10-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='send_at',
            new_name='sent_at',
        ),
    ]
