# Generated by Django 5.1.2 on 2024-10-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_rename_send_at_messages_sent_at'),
        ('chats', '0004_alter_chatparticipants_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatparticipants'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chats'),
        ),
    ]
