# Generated by Django 5.1.2 on 2024-10-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='tournament',
            new_name='tournament_id',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='tournament_stage',
            new_name='tournament_stage_id',
        ),
    ]
