# Generated by Django 5.1.2 on 2024-10-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_rename_tournament_matches_tournament_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='score_points',
        ),
    ]
