# Generated by Django 5.1.2 on 2024-10-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_players_score_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
