# Generated by Django 5.1.2 on 2024-10-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_players_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='tournament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='tournament_stage_id',
            field=models.IntegerField(null=True),
        ),
    ]
