# Generated by Django 5.1.2 on 2024-11-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size', models.IntegerField(default=16)),
                ('private', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('stage', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournaments')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('trophies', models.IntegerField()),
                ('seeding', models.IntegerField(default=None, null=True)),
                ('index', models.IntegerField(default=None, null=True)),
                ('still_in', models.BooleanField(default=True)),
                ('creator', models.BooleanField(default=False)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournaments')),
                ('stage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournamentstage')),
            ],
        ),
    ]
