# Generated by Django 5.1.2 on 2024-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipants',
            old_name='stage_index',
            new_name='index',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipants',
            name='stage',
        ),
    ]
