# Generated by Django 5.1.2 on 2024-10-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_stage_index_tournamentparticipants_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipants',
            old_name='index',
            new_name='seeding',
        ),
    ]
