# Generated by Django 5.1.2 on 2024-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_tournaments_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
