# Generated by Django 5.1.2 on 2024-10-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_index_tournamentparticipants_seeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipants',
            name='index',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipants',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournamentstage'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipants',
            name='seeding',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
