# Generated by Django 5.1.2 on 2024-10-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournamentparticipants_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournaments'),
        ),
    ]
