# Generated by Django 5.1.2 on 2024-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournaments_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='start_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
