# Generated by Django 5.1.2 on 2024-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournaments_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='is_public',
        ),
        migrations.AddField(
            model_name='tournaments',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
