# Generated by Django 5.1.1 on 2024-10-07 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20, unique=True)),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True, unique=True)),
                ('password', models.TextField(default=None, null=True)),
                ('accept_friend_request', models.BooleanField(default=True)),
                ('last_online', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_guest', models.BooleanField(default=True)),
                ('trophy', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('blocked_users', models.ManyToManyField(default=None, to='users.users')),
                ('django_user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('online_status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.onlinestatus')),
                ('own_profile_picture', models.ManyToManyField(default=None, related_name='own_profile_picture', to='users.profilepictures')),
                ('own_titles', models.ManyToManyField(default=None, related_name='own_titles', to='users.titles')),
                ('profile_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profilepictures')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.ranks')),
                ('title', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_title', to='users.titles')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_points', models.IntegerField(default=0)),
                ('cashed_points', models.IntegerField(default=0)),
                ('game_played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('game_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamemodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_since', models.DateTimeField(auto_now_add=True)),
                ('matches_play_against', models.PositiveIntegerField(default=0)),
                ('user1_win', models.PositiveIntegerField(default=0)),
                ('matches_play_together', models.PositiveIntegerField(default=0)),
                ('matches_win_together', models.PositiveIntegerField(default=0)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user1', to='users.users')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user2', to='users.users')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='users.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='users.users')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
