# Generated by Django 5.1.1 on 2024-10-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_matches_id_alter_tournaments_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, default=None, to='users.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='online_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.onlinestatus'),
        ),
        migrations.AlterField(
            model_name='users',
            name='own_profile_picture',
            field=models.ManyToManyField(blank=True, default=None, related_name='own_profile_picture', to='users.profilepictures'),
        ),
        migrations.AlterField(
            model_name='users',
            name='own_titles',
            field=models.ManyToManyField(blank=True, default=None, related_name='own_titles', to='users.titles'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profilepictures'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.ranks'),
        ),
        migrations.AlterField(
            model_name='users',
            name='title',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_title', to='users.titles'),
        ),
    ]
