# Generated by Django 5.1.1 on 2024-10-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_guest',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
