# Generated by Django 5.1.2 on 2024-10-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blocked_user',
            new_name='blocked',
        ),
    ]
