# Generated by Django 5.1.2 on 2024-10-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
