# Generated by Django 5.1.2 on 2024-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatparticipants',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='chatparticipants',
            name='username',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
