# Generated by Django 5.1.2 on 2024-10-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_user_chatparticipants_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
