# Generated by Django 5.1.2 on 2024-10-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatparticipants',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chats.chats'),
        ),
    ]
