# Generated by Django 5.1.2 on 2024-10-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chatparticipants_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatparticipants',
            name='username',
        ),
    ]
