# Generated by Django 5.1.1 on 2024-10-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_touched', models.IntegerField(default=0)),
                ('score_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('trophy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('n', models.IntegerField(default=1)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.FilePathField()),
                ('reload_time', models.DurationField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.CharField(default=['6', '1', '2', '4'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('state', models.CharField(default='lobby', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.PositiveSmallIntegerField(default=8)),
                ('nb_rounds', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.CharField(default=['7', '1', '0', '2'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_duration', models.DurationField()),
                ('state', models.CharField(default='lobby', max_length=20)),
                ('game_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamemodes')),
            ],
        ),
    ]
