# Generated by Django 5.1.1 on 2024-10-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users'),
        ),
        migrations.AddField(
            model_name='players',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users'),
        ),
        migrations.AddField(
            model_name='players',
            name='most_use_spells',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.spells'),
        ),
        migrations.AddField(
            model_name='teams',
            name='participants',
            field=models.ManyToManyField(to='games.players'),
        ),
        migrations.AddField(
            model_name='matches',
            name='teams',
            field=models.ManyToManyField(to='games.teams'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='participants',
            field=models.ManyToManyField(to='games.players'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='rounds',
            field=models.ManyToManyField(to='games.matches'),
        ),
        migrations.AddField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tournaments'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='max_players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.tournamentsize'),
        ),
    ]
