# Generated by Django 5.1.1 on 2024-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.CharField(default=['4', '6', '9', '5'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=['3', '9', '1', '4'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
