# Generated by Django 5.1.1 on 2024-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_matches_id_alter_tournaments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.CharField(default=['4', '2', '1', '6'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=['3', '0', '4', '2'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
