# Generated by Django 5.1.1 on 2024-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_matches_id_alter_tournaments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.CharField(default=['7', '0', '2', '1'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=['5', '4', '8', '2'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
