# Generated by Django 5.1.1 on 2024-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_matches_id_alter_tournaments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.CharField(default=['1', '1', '5', '4'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=['2', '4', '5', '9'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
