# Generated by Django 5.1.2 on 2024-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_matches_id_alter_tournaments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.CharField(default=['5', '9', '5', '5'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='id',
            field=models.CharField(default=['2', '3', '3', '6'], editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
